# Deploys a temporary environment for testing a version of the code when a pull request is created / updated with a 'deploy' label
name: Deploy PR Environment
concurrency: deploy

on:
  pull_request:
    types: [ labeled, synchronize ]

jobs:
  deploy-pr-environment:
    if: contains(github.event.pull_request.labels.*.name, 'deploy') || contains(github.event.pull_request.labels.*.name, 'deploy-to-production')
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: echo $EVENT_CONTEXT
      - name: Set pull request environment based on label deploy
        run: |
          echo "PR_DEPLOY_ENVIRONMENT=dev" >> $GITHUB_ENV
        if: contains(github.event.pull_request.labels.*.name, 'deploy')
      - name: Set pull request environment based on label deploy-to-production
        run: |
          echo "PR_DEPLOY_ENVIRONMENT=prod" >> $GITHUB_ENV
        if: contains(github.event.pull_request.labels.*.name, 'deploy-to-production')
      - run: |
          echo "Deploying environment for branch '${{ github.event.pull_request.head.ref }}' with labels '${{ join(github.event.pull_request.labels.*.name) }}' (pull request ${{ github.event.action }}) to environment ${PR_DEPLOY_ENVIRONMENT}!"
          echo "Contains output: ${{ contains(github.event.pull_request.labels.*.name, 'deploy-to-production') }}"
